### ISSUE TITLE
Add transmission resonator fit capability

### ISSUE THREAD

**Issue by SamuelWhiteley** [FaustinCarter/scraps#5]
Dear Faustin, could you please add a transmission (e.g. lambda/2 CPW resonator) fit function to scraps? A useful feature would be to toggle between hanger style and transmission style fitting code, where scraps could default to hanger resonators if it is not given this input for example.

The most common version of a transmission resonator fit function is a Lorentzian for the magnitude data to obtain loaded Q. Two references are:
- Goppl et al. J. Appl. Phys. 104, 113904 (2008), see equation (6)
- Kroll et al. Phys. Rev. Applied 11, 064053 (2019), see equation (2) in the supplementary information

You may not need to add an asymmetry fit parameter like the hanger function uses. If you are inspired the results of Khalil et al. J. Appl. Phys. 111, 054510 (2012) may point to a way of incorporating resonance asymmetry, although I have not dived deeply into that paper myself. The difficulty is that transmission resonators cannot independently yield Qi and Qe from a single measurement.

**Comment by FaustinCarter** [comment]
This was  closed as of v0.5.0!
