### ISSUE TITLE
AttributeError: module 'lmfit.models' has no attribute 'COMMON_DOC'

### ISSUE THREAD

**Issue by Emily-Linden** [FaustinCarter/scraps#8]
I tried installing lmfit and I keep getting an error saying 'lmfit.models' has no attribute 'COMMON_DOC'. I tried downloading it on two different computers and I keep getting the same thing. Here's the error message:

Input In [9], in <cell line: 1>()
----> 1 import scraps

File ~\Downloads\scraps-master\scraps_init_.py:1, in
----> 1 from scraps.fitsS21 import (
2 cmplxIQ_fit,
3 cmplxIQ_params,
4 hanger_fit,
5 hanger_params,
6 inline_fit,
7 inline_params,
8 )
9 from scraps.fitsSweep import f0_tlsAndMBT, qi_tlsAndMBT
10 from scraps.plot_tools import (
11 plotResListData,
12 plotResSweep3D,
(...)
15 plotResSweepParamsVsX,
16 )

File ~\Downloads\scraps-master\scraps\fitsS21_init_.py:3, in
1 from scraps.fitsS21.cmplxIQ import cmplxIQ_fit, cmplxIQ_params
2 from scraps.fitsS21.hanger_resonator import hanger_fit, hanger_params
----> 3 from scraps.fitsS21.inline_ground_terminated_resonator_s11 import (
4 inline_ground_terminated_fit,
5 inline_ground_terminated_params,
6 )
7 from scraps.fitsS21.inline_resonator import inline_fit, inline_params

File ~\Downloads\scraps-master\scraps\fitsS21\inline_ground_terminated_resonator_s11.py:11, in
9 import lmfit
10 import numpy as np
---> 11 from scraps.fitsS21 import baselines, utils
14 def cmplx_grounded_inline_s11(freqs, f0, df, qc, q0):
15 """An asymmetric lineshape vs frequency.
16
17 Pass df = 0 to recover the standard complex Lorentzian shape."""

File ~\Downloads\scraps-master\scraps\fitsS21\baselines.py:32, in
28 phi = p0 + p1 * x + p2 * x ** 2
29 return np.exp(1j * phi)
---> 32 class ModelMagBaseline(lmfit.Model):
33 doc = (
34 "lmfit model that fits a 2nd order polynomial as a function of reduced frequency."
35 + lmfit.models.COMMON_DOC
36 )
38 def init(self, *args, **kwargs):

File ~\Downloads\scraps-master\scraps\fitsS21\baselines.py:35, in ModelMagBaseline()
32 class ModelMagBaseline(lmfit.Model):
33 doc = (
34 "lmfit model that fits a 2nd order polynomial as a function of reduced frequency."
---> 35 + lmfit.models.COMMON_DOC
36 )
38 def init(self, *args, **kwargs):
39 super().init(mag, *args, **kwargs)

AttributeError: module 'lmfit.models' has no attribute 'COMMON_DOC'

**Comment by Emily-Linden** [comment]
lmfit 1.0.3 is not compatible. When installing scraps, the temporary fix is to then follow up with `pip install lmfit==1.0.2` after `pip install scraps`

**Comment by FaustinCarter** [comment]
I’ll take a look at this over the weekend. Happy to fix it up and cut a new release!

**Comment by FaustinCarter** [comment]
@Emily-Linden I've release v0.5.2 on both pypi and conda-forge. If you run into any other trouble, I'm happy to help.
